<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Version>2.0.0</Version>
    <PackageId>Otto.Theme.Avalonia</PackageId>
    <Authors>Keytrap</Authors>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/keytrap-x86/Otto.Theme</RepositoryUrl>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsAotCompatible>true</IsAotCompatible>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <RootNamespace>Otto.Theme.Avalonia</RootNamespace>
    <Description>Otto light and dark themes for Avalonia, compatible with Native AOT.</Description>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\readme.md" Pack="true" PackagePath="\" />
    <PackageReference Include="Avalonia" Version="12.1.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />
  </ItemGroup>
</Project>
